-- sqlpage-railway: the table SQLPage reads pages from when they are not on disk.
-- Do not edit this file after release: sqlx records a checksum of every applied migration.
CREATE TABLE IF NOT EXISTS sqlpage_files (
    path          VARCHAR(255) NOT NULL PRIMARY KEY,
    contents      BYTEA        NOT NULL,
    last_modified TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SQLPage caches compiled pages and re-reads a page when last_modified moves forward,
-- so bump it on every update.
CREATE OR REPLACE FUNCTION sqlpage_files_touch() RETURNS TRIGGER AS $$
BEGIN
  NEW.last_modified = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sqlpage_files_touch ON sqlpage_files;
CREATE TRIGGER sqlpage_files_touch BEFORE UPDATE ON sqlpage_files
FOR EACH ROW EXECUTE FUNCTION sqlpage_files_touch();
