-- sqlpage-railway: a small starter app. Everything here is ordinary data: edit or delete it at /admin/.
-- Do not edit this file after release: sqlx records a checksum of every applied migration.
CREATE TABLE IF NOT EXISTS guestbook (
    id         BIGSERIAL PRIMARY KEY,
    author     TEXT        NOT NULL,
    message    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO sqlpage_files (path, contents) VALUES ('index.sql', convert_to($page$-- The home page. It is stored in the sqlpage_files table: edit it at /admin/.

-- A form posts back to this page. Save the entry, then redirect so a refresh does not post it twice.
INSERT INTO guestbook (author, message)
SELECT left(trim(:author), 64), left(trim(:message), 500)
WHERE length(trim(coalesce(:author, ''))) > 0 AND length(trim(coalesce(:message, ''))) > 0
RETURNING 'redirect' AS component, '/?signed=' || id AS link;

SELECT 'hero' AS component,
    'Your SQLPage app is running' AS title,
    'Every page of this site is a SQL file stored in PostgreSQL, in the sqlpage_files table. Open the editor to change this page or add new ones: no rebuild, no redeploy.' AS description,
    '/admin/' AS link,
    'Open the page editor' AS link_text;

SELECT 'alert' AS component, 'Thanks, your message was saved.' AS title, 'green' AS color, 'check' AS icon
WHERE $signed IS NOT NULL;

SELECT 'form' AS component, 'Sign the guestbook' AS title, 'Save' AS validate;
SELECT 'author' AS name, 'Your name' AS label, TRUE AS required, 64 AS maxlength;
SELECT 'message' AS name, 'textarea' AS type, 'Message' AS label, TRUE AS required, 500 AS maxlength;

SELECT 'list' AS component,
    'Guestbook (' || (SELECT count(*) FROM guestbook) || ' entries)' AS title,
    'No entries yet. Be the first.' AS empty_title;
SELECT author AS title,
    message || ' (' || to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') || ' UTC)' AS description,
    'message' AS icon
FROM guestbook
ORDER BY id DESC
LIMIT 50;
$page$, 'UTF8'))
ON CONFLICT (path) DO NOTHING;
